# Generated by Django 5.2.5 on 2026-08-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_banner_alter_feereceipt_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_lectures', to='api.batch'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
