# Generated by Django 5.2.5 on 2026-09-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lecture_batch_lecture_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='allowed_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated student email IDs allowed in this batch'),
        ),
        migrations.AddField(
            model_name='course',
            name='allowed_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated student email IDs allowed in this batch'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='allowed_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated student email IDs allowed in this batch'),
        ),
        migrations.AddField(
            model_name='note',
            name='allowed_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated student email IDs allowed in this batch'),
        ),
        migrations.AddField(
            model_name='section',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.batch'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.course'),
        ),
    ]
