# Generated by Django 5.2.5 on 2026-09-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_batch_allowed_emails_course_allowed_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('trainer', 'Trainer'), ('faculty', 'Faculty')], default='student', max_length=20),
        ),
    ]
