# Generated by Django 5.2.5 on 2026-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer_permissions',
            field=models.TextField(blank=True, default='', help_text='Comma-separated box keys allowed for trainer'),
        ),
    ]
