server {
    listen 80;
    server_name YOUR_SERVER_IP_OR_DOMAIN;

    client_max_body_size 500M; # Max video upload size

    location /static/ {
        alias /home/ubuntu/clascic/django_backend/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/clascic/django_backend/pwbackend.sock;
    }
}
